# try:
#     do something that might cause an exception
# except (Error (as __)):
#     do this if there WAS an exception
#     (you can write multiple exceptions)
# else:
#     do this if there were NO exceptions
# finally:
#     do this no matter what
#
# raise Error("message") -> raise the specified error with the specified message
